#!/bin/bash

if [[ $1 == "" ]]; then
  cd /mnt/c/Users/droma/Projects/device
elif [[ $1 == "save" ]]; then
  cd /mnt/c/Users/droma/Projects/device
  git add -A
  wait
  git commit -m "$2"
  wait
  git push origin master
elif [[ $1 == "connect" ]]; then
  ssh pi@192.168.0.100
fi